### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by DIeMONdello** [ThatUsernameAlreadyExist/JCO-PM203-Fisheye-Ingenic-T20-P2P-camera-hacks#10]
приветствую!
как настроить отсылку фото по почте, не нашел описания?

**Comment by ThatUsernameAlreadyExist** [comment]
В /opt/media/sdc/config/sendmail.conf прописать все параметры почты (пример в sendmail.conf.dist).
В сервисах включить motion-detection и motion-mail, письмо должно отправляться при обнаружении движения.

**Comment by DIeMONdello** [comment]
не приходят письма, есть где логи посмотреть ?

**Comment by ThatUsernameAlreadyExist** [comment]
логов нет, в ближайшее время посмотрю и исправлю, если отправка email не работает (она взята без изменений из hack'a для Xiaomi-камер).

**Comment by ThatUsernameAlreadyExist** [comment]
Теперь должно работать: https://github.com/ThatUsernameAlreadyExist/JCO-PM203-Fisheye-Ingenic-T20-P2P-camera-hacks/commit/f79017641cc4094f824fbbd6a8aee28317fceff8

**Comment by DIeMONdello** [comment]
из mail.ru на yandex ничего не приходит :(

**Comment by ThatUsernameAlreadyExist** [comment]
Проверил отправку с mail.ru на yandex - письма проходят, возможно проблема в настройках.
Должны быть такие:
FROM="XXXXXX@mail.ru"
AUTH="XXXXXX@mail.ru"
PASS="***********"
TO="YYYYYYY@yandex.ru"
SERVER=smtp.mail.ru
PORT=465

Добавил тест отправки почты.
Запускать на камере подключившись по telnet: /opt/media/sdc/scripts/sendMailTest.sh
В выводе в строках "sendmail: recv:" будут ответы сервера.

**Comment by DIeMONdello** [comment]
выдает ошибку 
sendmail: applet not found

**Comment by ThatUsernameAlreadyExist** [comment]
Надо полностью весь хак на камере обновить, конкретно autorun.sh, но там и в других местах есть изменения (и перезагрузить камеру).

**Comment by DIeMONdello** [comment]
работает, спасибо!

**Comment by DIeMONdello** [comment]
но есть один вопрос, первая фотография поломанная снизу каждый раз, момент нагрузки в момент появления объекта и видимо процессор не успевает, есть возможность решения?

**Comment by ThatUsernameAlreadyExist** [comment]
Да, видел это. Посмотрю, что можно сделать.

**Comment by ThatUsernameAlreadyExist** [comment]
Теперь изображение при просмотре в браузере и отправке на email портиться не должно.

**Comment by DIeMONdello** [comment]
работает отлично!
