### ISSUE TITLE
Stuck at step 8

### ISSUE THREAD

**Issue by Nanich87** [ThatUsernameAlreadyExist/JCO-PM203-Fisheye-Ingenic-T20-P2P-camera-hacks#6]
I have successfully applied the patch, but after rebooting my camera, neither port 80 is open nor 554. Trying to access cameraip:9999 in browser shows the following message: [Error]no such command!

**Comment by ThatUsernameAlreadyExist** [comment]
Check in telnet that your microSD card is mounted as /opt/media/mmcblk0p1/
Try different microSD card or reformat your current card as FAT32 (replacing a microSD card helped other users with the same problem).

**Comment by magpern** [comment]
@ThatUsernameAlreadyExist I have the exact same problem. I have a sannce i41hd with v3.1.34.
I have done nothing to the camera. I just formated a sdcard as FAT32 with 32kb allocation size.
Put it into the camera, turned power on, telnet to the camera, and run the install.sh
Console say
![image](https://user-images.githubusercontent.com/6589760/74886435-7279fe80-5378-11ea-8303-afdb1328c9bc.png)
camera reboots... then nothing else happens.
Camera works just as it used too. It is still showing feed in the Danale app, and it will not allow me to connect to https://192.168.1.84

sdcard is mounted
![image](https://user-images.githubusercontent.com/6589760/74886535-b66d0380-5378-11ea-9490-058e67e8d818.png)

Have I missed anything? Do I need to install another firmware first, then the sdcard thing with the ./install.sh ?

**Comment by ThatUsernameAlreadyExist** [comment]
I think there is some problem with SD card mounting.
My camera don't have "mmcblk0p1->mmcblk0" entry:
```
root@Fisheye:/opt/media# ls -la
total 64
drwxr-xr-x    4 root     root             0 Jan  1  1970 .
drwxr-xr-x    7 root     root             0 Jan  1  1970 ..
drwxrwxrwx   13 root     root         32768 Jan  1  1970 mmcblk0p1
drwxrwxrwx   13 root     root         32768 Jan  1  1970 sdc
```
Please, paste here output of command 'mount'

**Comment by magpern** [comment]
@ThatUsernameAlreadyExist this is the outup of mount

![image](https://user-images.githubusercontent.com/6589760/74979550-1faf4e00-542f-11ea-8e45-a1e030260e53.png)

(I failed to paste the output from putty... it would not format in github)

**Comment by ThatUsernameAlreadyExist** [comment]
Unpack and copy (with replacing) attached file 'local.rc' to 'patch' folder on microsd and try reinstall hack via telnet.
[local.zip](https://github.com/ThatUsernameAlreadyExist/JCO-PM203-Fisheye-Ingenic-T20-P2P-camera-hacks/files/4233083/local.zip)

**Comment by magpern** [comment]
@ThatUsernameAlreadyExist Wow! That worked! Now SD card is mounted
![image](https://user-images.githubusercontent.com/6589760/74981837-453e5680-5433-11ea-8824-9ba2f39dbaac.png)
and it responds on http... but it wants me to enter basic http encryption (user / password)?
Where do I find this?

**Comment by ThatUsernameAlreadyExist** [comment]
Good news!
Login/password is equal to telnet: root/jco66688 (can be changed on settings page in web interface).

**Comment by magpern** [comment]
Thanks it worked!
I can confirm the sannce i41hd with version v3.1.34 works now!
@Nanich87 I assume it will work for you too if you change the local.rc
